### ISSUE TITLE
Warning: Use of undefined constant DEVEL_ERROR_HANDLER_STANDARD

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/devel#84] opened 2019-10-29 01:16 UTC
This was just a warning, so could be ignored, but still decided to report. While upgrading a D7 website to Backdrop, running the /core/update.php file has given:

`Warning: Use of undefined constant DEVEL_ERROR_HANDLER_STANDARD - assumed 'DEVEL_ERROR_HANDLER_STANDARD' (this will throw an Error in a future version of PHP) in devel_update_1000() (line 69 of /var/www/docroot/modules/devel/devel.install).`

**Comment by herbdool** [comment] 2019-12-09 19:29
This is duplicate of this older issue: https://github.com/backdrop-contrib/devel/issues/34. I'll update the title on the older one.

**Closed as completed** 2019-12-09 19:30 UTC
