### ISSUE TITLE
ERROR: count(): Parameter must be an array or an object that implements Countable on line 1724 in devel.module

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/devel#87] opened 2019-11-03 19:21 UTC
The 1.x-1.x branch of Devel gives the error in title on a system with PHP 7.3.9. Looks like this was discussed on https://www.drupal.org/project/devel/issues/2959508 and fixed by https://git.drupalcode.org/project/devel/commit/bd4061f I'll create a PR with similar fix.

**Comment by klonos** [comment] 2019-11-04 21:15
Actually, this is a duplicate of #44

**Closed as completed by klonos** 2019-11-04 21:15 UTC
